export { Comment } from './model/types/comment'
export { CommentsList } from './ui/CommentsList/CommentsList'
export { SkeletonCommentsList } from './ui/SkeletonCommentsList/SkeletonCommentsList'
export { CommentMock } from './mocks/data'
export { AddNewComment } from './ui/AddNewComment/AddNewComment'
