export { articleReducer } from './model/slice/articleSlice'
export { ArticleSchema } from './model/types/articleSchema'
export { Article as ArticleDetail } from './ui/Article/Article'
export { getArticleData } from './model/selectors/articleDetail'
export { ArticleMock } from './mocks/data'
export { ArticleList } from './ui/ArticleList/ArticleList'
